name: Deploy to EC2 Instance
on:
  push:
    branches:
      - deploy_code_on_private_ip_instance
jobs:
  deploy:
    runs-on: ubuntu-latest  # Use a Linux runner
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION=: us-east-1

      - name: Install tools
        run: |
         sudo apt-get update
         sudo apt-get install -y ssh rsync awscli    

      - name: Connect to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@172.31.95.238 "sudo apt-get update"

      - name: Transfer code
        run: |
          rsync -avz ./ ubuntu@172.31.95.238:/tmp/

      # - name: Run installation or startup commands
      #   run: |
      #     ssh ubuntu@172.31.95.238 "cd /path/to/deploy/directory && npm install && npm start"
    
    
   
    


    
               
      
           
