name: Angular GitHub CI
on:
  push:
    branches:
      - deploy_code_on_private_ip_instance

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.2
      - name: Setting environment variables..
        run: |
          echo "AWS_DEFAULT_REGION=${{secrets.AWS_REGION}}" >> $GITHUB_ENV
          echo "AWS_SG_NAME=${{secrets.SG_NAME}}" >> $GITHUB_ENV
      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32    
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}

      - name: Install tools
        run: |
         sudo apt-get update
         sudo apt-get install -y ssh rsync awscli    

      - name: Connect to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@172.31.95.238 "sudo apt-get update"

      - name: Transfer code
        run: |
          rsync -avz ./ ubuntu@172.31.95.238:/tmp/

      # - name: Run installation or startup commands
      #   run: |
      #     ssh ubuntu@172.31.95.238 "cd /path/to/deploy/directory && npm install && npm start"
    
    
   
    


    
               
      
           
