# This is a basic workflow to help you get started with Actions

name: Dev Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ ohio ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Get Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      # Updates security group in AWS so the github actions runner can ssh into the server
      - name: Update AWS Security Group Rule
        run: |
          aws ec2 authorize-security-group-ingress --group-id sg-0427701405cb5f8b1 --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
   
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir ../feature
          cp -TR www ../feature
          tar -cvf deploy.tar ../feature/
          echo $DB_FILE >> test.php
        env:
          DB_FILE : ${{secrets.SECRET_TEXT}}
          
      - name: Upload files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          source: "deploy.tar, test.php"
          target: "/var/www"
          
      - name: Deploy Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            tar -xvf /var/www/deploy.tar -C "/var/www"
            cp /var/www/test.php /var/www/feature/application/test.php
            rm /var/www/deploy.tar
            rm /var/www/test.php
            sudo chmod -R 775 /var/www/feature/
            sudo chgrp -R www-data /var/www/feature/
          
          
          
          
          
          
