name: ec2-rds Deploy


on:
  
  push:
    branches: [ aws-ec2-rds ]

  
  workflow_dispatch:


jobs:
 
  build:
    
    runs-on: ubuntu-latest

   
    steps:
     
      - uses: actions/checkout@v2
      
      - name: Get Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          
      
      - name: Update AWS Security Group Rule
        run: |
          aws ec2 authorize-security-group-ingress --group-id sg-0427701405cb5f8b1 --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
   
      
      - name: Run a multi-line script
        run: |
          mkdir ../warco
          cp -TR www ../warco
          tar -cvf deploy.tar ../warco/
          echo $DB_FILE >> dbconnect.php
        env:
          DB_FILE : ${{secrets.Secret_text}}
          
      - name: Upload files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          source: "deploy.tar, dbconnect.php"
          target: "/var/www"
          
      - name: Deploy Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            tar -xvf /var/www/deploy.tar -C "/var/www"
            cp /var/www/dbconnect.php /var/www/warco/application/dbconnect.php
            rm /var/www/deploy.tar
            rm /var/www/dbconnect.php
            sudo chmod -R 775 /var/www/warco/
            sudo chgrp -R www-data /var/www/warco/
          
          
          
