name: Create EC2 Instance

on:
  push:
    branches:
      - cat-secrets

jobs:
  create-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      

      - name: Run a multi-line script
        run: |
          
          # echo $SECRET_TEXT >> test.txt 
          echo ${{secrets.SECRET_VALUE}} | sed 's/./& /g'
          # echo -n "${{ secrets.SECRET_VALUE }}" >> foo && cut -c1-3 foo && cut -c15
          
          
            

      # - name: Create EC2 Instance
      #   run: |
      #     aws ec2 run-instances \
      #       --image-id ami-0261755bbcb8c4a84 \
      #       --instance-type t2.micro \
      #       --key-name yahya-test-key-pair \
      #       --subnet-id subnet-01c079ede545c1bb7 \
      #       --security-group-ids sg-014ddc6112fb66838 \
      #       --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=yahya-test-instance}]'
