name: Connect to EC2 private Ip
on:
  push:
    branches:
      - ec2-private-ip

jobs:
  connect-to-instance:
    runs-on: ubuntu-latest  # Replace with your desired runner OS

    steps:
    - uses: actions/checkout@v3  # Checkout the repository code

    - name: Install awscli
      run: |
        sudo apt-get update
        sudo apt-get install awscli

    - name: Connect to EC2 instance
      run: |
        aws ec2-instance-connect open-tunnel \
          --instance-id i-00f80135530d27541 \
          --private-ip-address 10.0.7.122 \
          --remote-port 22 \
          --instance-connect-endpoint-id eice-062ca1117bb639e9f \
          --region us-east-1
        # Replace placeholders with your actual values

    - name: Run commands on the instance (optional)
      run: |
        ssh -o ProxyCommand="ssh -i yahya-key-2024 ubuntu@localhost:22" ubuntu@10.0.7.122 sudo mkdir test
        # Replace placeholders with your pem key path, username, instance IP, and desired command
