name: Example Workflow

on:
  push:
    branches:
      - cat-secrets

jobs:
  example_job:
    runs-on: ubuntu-latest
    
    env:
      MY_SECRET: ${{ secrets.SECRET_VALUE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use secret in a step
      run: |
        echo "Using secret: $MY_SECRET"
        # Perform other actions using the secret
